GET http://localhost:3001/fx_rates/eur/usd
Content-Type: application/json
Authorization: Token _JzeGOOrwXmCX7EPIMeqo6dO35bcbqEU5u4Xpi2TEC0zYsS6Oze7u8Ue-emaSmRB8OfJ87qL-t7C0wLIz-wiyLe8mWmisFwwEmmslNXqixsQESxtyZi1GBDhAOTy83NoXl8edmxqXoRtx_fzKtatZcckSqmcznosZuZ-FXzyOhrLg2hKgfqSacS5qf2_uPnhXmRdafggzvGjpXAOxAtaFyvcY6cl6iclXsa5fBu6FdZK91l7nFKGMmAavhrkOt_Yxh3XGGimHtu0fMzk0Ccphlnep85DOT8yWstrhUEnBQ6E