
###
GET http://{{host}}/hello

###
POST http://{{host}}/simulations
Content-type: application/json

{
    "method": "GET",
	"path": "/hello",
	"status": 500,
	"response": { "message": "server is down!" }
}

###
GET http://{{host}}/simulations

###
DELETE http://{{host}}/simulations


###
GET http://{{host}}/hello
