# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install dependencies
      run: npm install

    - name: Check code syntax, lint and spelling
      run: npm run checks
    
    - name: Start webserver for tests
      run: npm run start &
      # The '&' symbol runs the command in the background, allowing us to continue with the next step immediately.

    - name: Wait for webserver to start
      run: sleep 3
      # This step waits for 3 seconds to allow the webserver to start up before running the tests.

    - name: Run acceptance tests
      run: npm test
